# Generated by Django 4.2.1 on 2023-05-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_staff_created_alter_staff_name_alter_staff_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCourse',
            fields=[
                ('mainCourseId', models.AutoField(db_column='mainCourseId', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'main_course',
            },
        ),
    ]
