# Generated by Django 4.2.1 on 2023-06-08 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_staff_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('user', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Aktywne', 'Aktywne'), ('Gotowe', 'Gotowe'), ('Zakonczone', 'Zakonczone')], max_length=32)),
                ('mainCourse', models.ForeignKey(on_delete=models.SET('Danie usuniete'), to='api.maincourse')),
            ],
        ),
    ]
