# Generated by Django 4.2.6 on 2023-11-22 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_order_maincourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mainCourse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.maincourse'),
        ),
    ]
