# Generated by Django 4.2.6 on 2023-11-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_order_maincourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Aktywne', 'Aktywne'), ('Gotowe', 'Gotowe'), ('Zakonczone', 'Zakonczone')], default='aktywne', max_length=32),
        ),
    ]
