# Generated by Django 4.2.6 on 2023-11-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincourse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main_course_images/'),
        ),
    ]
