# Generated by Django 4.2.6 on 2023-11-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_maincourse_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Aktywne', 'Aktywne'), ('Gotowe', 'Gotowe'), ('Zakonczone', 'Zakonczone')], default='Aktywne', max_length=32),
        ),
    ]
