# Generated by Django 4.2.6 on 2024-01-14 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='role',
        ),
    ]
