# Generated by Django 4.2.6 on 2024-01-24 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_staff_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='role',
        ),
    ]
