version: '3.9'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'kantyna'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'

  
  backend:
    build: 
      context: ./system_zamowien/system_zamowien
    env_file:
      - ./system_zamowien/system_zamowien/.env
    ports:
      - '8000:8000'
    depends_on:
      - db

  frontend:
    build:
      context: ./app
    ports:
      - '8080:8080'